package com.vfi.android.domain.entities.consts;

public class HostRespError {
    public final static int HOST_RESP_ERR_Other    = -1;
    public final static int HOST_RESP_ERR_01       = 1;
    public final static int HOST_RESP_ERR_02       = 2;
    public final static int HOST_RESP_ERR_03       = 3;
    public final static int HOST_RESP_ERR_04       = 4;
    public final static int HOST_RESP_ERR_05       = 5;
    public final static int HOST_RESP_ERR_07       = 7;
    public final static int HOST_RESP_ERR_12       = 12;
    public final static int HOST_RESP_ERR_13       = 13;
    public final static int HOST_RESP_ERR_14       = 14;
    public final static int HOST_RESP_ERR_15       = 15;
    public final static int HOST_RESP_ERR_19       = 19;
    public final static int HOST_RESP_ERR_21       = 21;
    public final static int HOST_RESP_ERR_25       = 25;
    public final static int HOST_RESP_ERR_28       = 28;
    public final static int HOST_RESP_ERR_30       = 30;
    public final static int HOST_RESP_ERR_31       = 31;
    public final static int HOST_RESP_ERR_41       = 41;
    public final static int HOST_RESP_ERR_43       = 43;
    public final static int HOST_RESP_ERR_51       = 51;
    public final static int HOST_RESP_ERR_52       = 52;
    public final static int HOST_RESP_ERR_53       = 53;
    public final static int HOST_RESP_ERR_54       = 54;
    public final static int HOST_RESP_ERR_55       = 55;
    public final static int HOST_RESP_ERR_57       = 57;
    public final static int HOST_RESP_ERR_58       = 58;
    public final static int HOST_RESP_ERR_67       = 67;
    public final static int HOST_RESP_ERR_76       = 76;
    public final static int HOST_RESP_ERR_77       = 77;
    public final static int HOST_RESP_ERR_78       = 78;
    public final static int HOST_RESP_ERR_80       = 80;
    public final static int HOST_RESP_ERR_81       = 81;
    public final static int HOST_RESP_ERR_82       = 82;
    public final static int HOST_RESP_ERR_83       = 83;
    public final static int HOST_RESP_ERR_85       = 85;
    public final static int HOST_RESP_ERR_89       = 89;
    public final static int HOST_RESP_ERR_91       = 91;
    public final static int HOST_RESP_ERR_93       = 93;
    public final static int HOST_RESP_ERR_94       = 94;
    public final static int HOST_RESP_ERR_95       = 95;
    public final static int HOST_RESP_ERR_96       = 96;
}
